---
abstract: 'Resolve database connection on the environment has many database servers.'
author:
  - '=over'
build_requires:
  ExtUtils::MakeMaker: 6.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: DBIx-DBHResolver
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Carp: 0
  Class::Accessor::Fast: 0
  Config::Any: 0
  DBI: 0
  Data::Util: 0
  Filter::Util::Call: 0
  Hash::Merge::Simple: 0
  Try::Tiny: 0
  UNIVERSAL::require: 0
  YAML: 0
  parent: 0
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/arisawa/p5-dbix-dbhresolver.git
version: 0.12
